spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devple_ledger
    hikari:
      username: devple_ledger
      password: devple_ledger
      maximum-pool-size: 5
      minimum-idle: 2
  flyway:
    locations: classpath:db/common
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: ledger-secret-key
  validity: 86400
  refresh: 2592000
